# Termini associati alla dinamica del sistema
m: 12 # massa in [kg]
d: 0.338
l: 0.457

# Coefficienti di Damping



X_u_dot: 0



X_u : 0.1174
Y_v : 0.2294
Z_w : 0.1545
N_r: 0.07

target_x : 15
target_y : 15
target_z : 5

MAP_NE_x: 20 #vertice nord est mappa, coordinata x
MAP_NE_y: 20 #vertice nord est mappa, coordinata y
MAP_NW_x: -20 #vertice nord ovest mappa, coordinata x
MAP_NW_y: 20 #vertice nord ovest mappa, coordinata y
MAP_SW_x: -20 #vertice sud ovest mappa, coordinata x
MAP_SW_y: -20 #vertice sud ovest mappa, coordinata y
MAP_SE_x: 20 #vertice sud est mappa, coordinata x
MAP_SE_y: -20 #vertice sud est mappa, coordinata y

is_Spline_xy: False  # Linear: False, Spline: True
is_Spline_z: False  # Linear: False, Spline: True