# Termini associati alla dinamica del sistema
m: 12 # massa in [kg]
d: 0.338
l: 0.457

# Coefficienti di Damping

Y_v_dot: 0
Y_v: 0
Y_r: 0
X_u_dot: 0
X_u: 0
Z_w: 0
N_r: 0
N_r_r: 0
N_v : 0

target_x : 15
target_y : 15
target_z : 15

MAP_NE_x: 20 #vertice nord est mappa, coordinata x
MAP_NE_y: 20 #vertice nord est mappa, coordinata y
MAP_NW_x: -20 #vertice nord ovest mappa, coordinata x
MAP_NW_y: 20 #vertice nord ovest mappa, coordinata y
MAP_SW_x: -20 #vertice sud ovest mappa, coordinata x
MAP_SW_y: -20 #vertice sud ovest mappa, coordinata y
MAP_SE_x: 20 #vertice sud est mappa, coordinata x
MAP_SE_y: -20 #vertice sud est mappa, coordinata y
freq_to_gazebo: 10 # frequenza pubblicazione pose su gazebo

dt: 0.1 # tempo di campionamento
